### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by joshua750** [raysummee/expire_it#7]
Totally useless not working test ios simulator

**Comment by raysummee** [comment]
Hi @joshua750. 

We are extremely regretted to know that the package is not working for you. Can you please provide us the reproducible steps. We will fix it shortly. 

Thanks

**Comment by raysummee** [comment]
HI @joshua750. 

Just to be sure. Did you add `ExpireIt.controller = UserDefineExpireController(expiryDate: date);` in main function. Without this the expire functionality is disabled.

**Comment by joshua750** [comment]
<img width="1440" alt="Screenshot 2023-10-10 at 3 32 37 PM" src="https://github.com/raysummee/expire_it/assets/9497422/07c41e34-daa8-43c1-af38-2a16a154533f">
here is my code sacreenshot i add 2022 date  but app still work

**Comment by joshua750** [comment]
import 'package:expire_it/expire_it.dart';
import 'package:flutter/material.dart';
import 'package:transporter/Home.dart';

import 'Expire.dart';

void main() {
  ExpireIt.controller = UserDefineExpireController(expiryDate: DateTime(2022));

  runApp( MyApp());
}

class MyApp extends StatelessWidget {
   MyApp({super.key});
  // Define the expiration date
  // DateTime expirationDate = DateTime(2023, 10, 17);
  //
  //  // Function to check if the app is expired
  //  bool isAppExpired() {
  //    DateTime currentDate = DateTime.now();
  //    return currentDate.isAfter(expirationDate);
  //  }

  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {

    return MaterialApp(
      debugShowCheckedModeBanner: false,
      title: 'Flutter Demo',
      theme: ThemeData(
        // This is the theme of your application.
        //
        // TRY THIS: Try running your application with "flutter run". You'll see
        // the application has a blue toolbar. Then, without quitting the app,
        // try changing the seedColor in the colorScheme below to Colors.green
        // and then invoke "hot reload" (save your changes or press the "hot
        // reload" button in a Flutter-supported IDE, or press "r" if you used
        // the command line to start the app).
        //
        // Notice that the counter didn't reset back to zero; the application
        // state is not lost during the reload. To reset the state, use hot
        // restart instead.
        //
        // This works for code too, not just values: Most code changes can be
        // tested with just a hot reload.
        colorScheme: ColorScheme.fromSeed(seedColor: Colors.deepPurple),
        useMaterial3: true,
      ), home: Home());

    // isAppExpired() ? ExpiredScreen() :
  }
}

also copy code

**Comment by raysummee** [comment]
Thanks for the reproducible codes. I'll fix it and update here.

**Comment by raysummee** [comment]
HI @joshua750. I was not able to see this ui logic in your code above. Please make sure you add this. 

```dart
ExpireIt(
    expireBuilder: (context) {
        return const Center(
            child: Text("Expired"),
        );
    },
    builder: (context) {
        return const Center(
            child: Text("Home screen"),
        );
    },
    loadingBuilder: (context) {
        return const Center(
            child: CircularProgressIndicator(),
        );
    },
),

```

Also I would request you to check the example app. If this works or not. Thanks

**Comment by joshua750** [comment]
This is just ui code which give status of expiration  but according to my code once it expire app should not work or should I implement logic according to the expiration example if it's expired I need perform another's task?

**Comment by raysummee** [comment]
Yes. You may implement the logic according to the expiration example. As the package is still in development listener is not implemented yet, only builder was implement. 

You may show another widget when it is expiration state. That way you can restrict user from accessing the app after expiration. 

If you need the listener functionality urgently please create another issue with the feature request.  

For now I'll close this issue. If you want anything else please feel free to reopen this issue anytime. 

Thanks
